/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package in.technobuff.app

import spock.lang.Specification

class AppTest extends Specification {

    /*def checkEquals(expectedResult,actualResult){
        if(expectedResult.size()== actualResult.size()) {
            for(def index=0 ; index< expectedResult.size() ;index++) {
                if(!actualResult.get(index).equals(expectedResult.get(index))) return false ;
            }
            return true ;
        }
        return false ;
    }*/
}
