/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package in.technobuff.app;

public class App {
    public static CoinChangeMachine coinChangeMachine ;
    public static void main(String[] args) {
        new App().setupCoinChangeMachine() ;

        coinChangeMachine.calculateChange(287) ;
    }

    private static void setupCoinChangeMachine() {
        coinChangeMachine = new CoinChangeMachine() ;
        coinChangeMachine.setCurrency("INR") ;
    }
}
